arb-dir: lib/l10n
output-class: FeaturebaseLocalizations
output-localization-file: featurebase_localizations.dart
output-dir: lib/l10n/generated
template-arb-file: package_en.arb
preferred-supported-locales: ["en"]
synthetic-package: false
nullable-getter: false
format: true
untranslated-messages-file: lib/l10n/untranslated.json
