name: featurebase
description: "Featurebase Unofficial Flutter SDK"
version: 0.7.0
homepage: https://github.com/ae1dev/flutter_featurebase

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - featurebase
  - help-center
  - changelog

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  featurebase_dart: ^0.0.9
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  custom_top_navigator_plus: ^0.0.4
  flutter_svg: ^2.0.16
  flutter_widget_from_html: ^0.15.3
  cached_network_image: ^3.4.1
  styled_text: ^9.0.0-beta-4
  searchfield: ^1.2.2
  easy_infinite_pagination: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.7.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  flutter_gen: ^5.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/hero/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt_Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt_Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt_Bold.ttf
          weight: 700
